### ISSUE TITLE
Malfunctioning of the Check button when h5p-highlight-the-words inserted in interactive book.

### ISSUE THREAD

**Issue by rezeau** [otacke/h5p-highlight-the-words#8]
Malfunctioning of the Check button when h5p-highlight-the-words inserted in interactive book.
Steps to reproduce
1.- Use h5p-highlight-the-words latest version 0.1.5 on a dev site
2.- h5p-column create a new branch, e.g. testing_highlight and, in semantics, add "H5P.HighlightTheWords 0.1", and in h5p-column.js var isTasks add "H5P.HighlightTheWords"
3.- Create an interactive book
4.- Create page 1 with only a Text content in it
5.- Create page 2 with a Multiple Choice question in it
6.- Create page 3 with an HighlightTheWords content in it. Options enable Show solutions.
7.- Save and run the H5P Interactive Book
8.- Page 1 : read the text
9.- Navigate to page 2 (with the MCQ question) : The Check button below the question appears very briefly then disappears!
10. Navigate to page 3 (with the HighlightTheWords content) Colour some words, then click the Check button: the score is not displayed, but the Show solution and Retry buttons are displayed.
11. Click the Show solution button: nothing happens.
12. Press the F5 key on your keyboard to refresh the page: colour some words, click the Check button, now things work as expected, the Score is displayed, and the Show solution button works, etc.
13.- Navigate back to page 2 (with the MCQ content) and now you see that the Check button is displayed.

**Comment by otacke** [comment]
@rezeau Please feel free to fix that yourself. I do not intend to work on this content type anymore.

**Comment by rezeau** [comment]
OK, I'll have a look.
